### ISSUE TITLE
Provide an function to change the number of simultaneous downloads in the code side

### ISSUE THREAD

**Issue by deeppandya** [lingochamp/FileDownloader#168]
I've created an filedownload.properties file under my app assets folder, and in there I've the following property defined:
download.max-network-thread-count=4

I want 4 downloads at a time, if another get started in the meantime it should be queued.
But it's not working. it's not allowing me to download more than 3 downloads at the same time.

**Comment by deeppandya** [comment]
is it possible to make it configurable instead of using properties file ? because according to my requirement, i have to add a settings option where user can select number of simultaneous downloads.

**Comment by Jacksgong** [comment]
I checked in Demo project, (Set the `download.max-network-thread-count=4` in `demo/src/main/assets/filedownloader.properties`, And Test Download simultaneously in `TasksManagerDemoActivity`), Everything works well. Please check your code again, I think there would be other mistakes make your problem.


Recommends to check the log which is printed by `FileDownloadProperties`.

**Comment by Jacksgong** [comment]
For your requirement:

1. `FileDownloader#pauseAll` and `FileDownloader#unBindService()` and Kill the filedownloader process.
2. [Setting value inside filedownloader.properties at run time](http://stackoverflow.com/questions/13501675/setting-value-inside-property-file-at-run-time).

**Comment by Jacksgong** [comment]
You know what, I will support Set the Number of simultaneous downloads at runtime, but for Robust it would in very harsh terms. So you need to pay attention to  several points:

1. For Compatibility: FileDownloader will use the value in `filedownloader.properties` as default, at this point, the value you set at runtime would not be persistent store by FileDownloader, it means you need persistent it by yourself and FileDownloader will provide a `FileDownloader#init` function with new params, and you need to init FileDownloader by this way each time.

2. For Robust: The number of simultaneous downloads is very dangerous value, because it is the count of the thread of FileDownloader network thread pool, it means FileDownloader need to shut down old one and create new one with the value you offered for Robust, at this point, you need to invoke `FileDownloader#pauseAll()` before set the value, otherwise you may receive a throwable if the thread pool is working.

**Comment by deeppandya** [comment]
Hello,

Assets in android are readonly file system. so from the code side, we can't modify the property. 
is it possible for you to provide an option to change the number of simultaneous downloads ?

Thanks

**Comment by Jacksgong** [comment]
Supported by bellow functions:

1. https://github.com/lingochamp/FileDownloader/blob/427ce3ff5bda4c6366723e9ca1432d15e2c8eedd/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L72

2. https://github.com/lingochamp/FileDownloader/blob/427ce3ff5bda4c6366723e9ca1432d15e2c8eedd/library/src/main/java/com/liulishuo/filedownloader/FileDownloader.java#L548

**Comment by Jacksgong** [comment]
Enhancement since [v0.3.2](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.2)
