### ISSUE TITLE
Downloading paused when the activity is onPause() state

### ISSUE THREAD

**Issue by sudarshaana** [lingochamp/FileDownloader#174]
Reading the wiki it seems that it support background downloading. But when I am using **SINGLE TASK TEST** and start to download a file everything is going well. But when I am going bac to the main activity the downloading is paused.

If downloading in the background is supported how to use it?
I am confused.

**Comment by Jacksgong** [comment]
OK, In **SINGLE TASK TEST** , We pause downloading tasks manually in [`onDestroy`](https://github.com/lingochamp/FileDownloader/blob/cc629a48e7add97187d31cd3c87b3af93dc095c8/demo/src/main/java/com/liulishuo/filedownloader/demo/SingleTaskTestActivity.java#L114), So it is paused when you back to the main activity.

---

Yes absolutely, FileDownloader support downloading in the background. It isn't bound Activity Lifecycle. But there is only one thing you need to notice: because if you set the listener when you start a download task in the Activity,  In the normal case is when you left the Activity, you will lose the holder of the listener, so you have to manage you own listeners for 'downloading in background'. **You can handle such problem Ref [here](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124)**.

**Comment by sudarshaana** [comment]
Thanks.
I'm checking this stuff.
