### ISSUE TITLE
resume after Error

### ISSUE THREAD

**Issue by sajadshokri** [lingochamp/FileDownloader#229]
if a task has faced error and i call `currentTask.start()` an exception rises:
> Caused by: java.lang.IllegalStateException: This task is dirty to restart, If you want to reuse this task, please invoke #reuse method manually and retry to restart again.

and if i call `reuse` there will be another exception:
> java.lang.IllegalStateException: the messenger is working, can't re-appointment for 538416338@com.liulishuo.filedownloader.FileDownloadTask@1990b258

what else should i do?

**Comment by Jacksgong** [comment]
Through bellow exception:

> java.lang.IllegalStateException: the messenger is working, can't re-appointment for 538416338@com.liulishuo.filedownloader.FileDownloadTask@1990b258

because you invoke `reuse` in the `FileDownloadListener#error` method, and FileDownloader makes the task's messenger free after the error message arrived, it means the messenger is freed after `FileDownloadListener#error` invoked.

---

I will free the messenger before message arrived in next version.

**Comment by Jacksgong** [comment]
Fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).
