### ISSUE TITLE
Resume a download task has a Throwable.

### ISSUE THREAD

**Issue by xiejinglan** [lingochamp/FileDownloader#265]
com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 412, 
 request headers: If-Match: "853934bff57cc1:624d"
Range: bytes=6350674-
Cache-Control: no-cache

 response headers: Date: Tue, 16 Aug 2016 01:21:02 GMT
Content-Length: 1306
Content-Type: text/html
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET

It,s has a throwable when i run your demo to resume a download task.

**Comment by Jacksgong** [comment]
In the demo project, URLs are from the Internet, there occur the response code is non-[200,300) is normal, It just presents what you can meet when you occur such problem.

**Comment by xiejinglan** [comment]
but i try to remove the " If-Match" from the  http header ,it's running ok.

**Comment by Jacksgong** [comment]
This problem is more likely to be server-side.

**Comment by Jacksgong** [comment]
In FileDownloader every ETags(which would be used in the value of "If-Match") must be got from the server( FileDownloader never generate it by local), So if you receive 412 because of can't match ETag in "If-Match", it more likely the problem in the server.

In the official document, we may get the response status code 412, because bellow conditions in request-header match failed:

```
If-Match
If-Modified-Since
If-None-Match
If-Range
If-Unmodified-Since
```
---

Normally, If FileDownloader provides the ETag isn't the latest one in the server, FileDownloader will receive the response status code 200, and FileDownloader will start the task from the length-0, otherwise FileDownloader will receive the response status code 206, and FileDownloader will resume the task from the breakpoint.

---

In the current version(0.3.4) FileDownloader, you can handle such the reponse status code by following way:

Step 1. clear the ETag stored in the filedownloader database : `FileDownloader.getImpl().clear(downloadId, targetPath)`.
Step 2. start the task normally.

**Comment by Jacksgong** [comment]
@xiejinglan any problem?
