### ISSUE TITLE
Speed - I am not getting proper speed compare to other few one

### ISSUE THREAD

**Issue by Kishankondhiya** [lingochamp/FileDownloader#268]
Hello sir hope you are fine,
I have just implemented your downloader in my application but i am getting lower speed in compare with https://github.com/majidgolshadi/Android-Download-Manager-Pro
Is something went wrong with me or what ?
is there any way to get more speed in your downloader ?
because i found a perfect downloader this is but just facing speed issue can you please let me know as soon !!

**Comment by Jacksgong** [comment]
Thanks.

Speed and power are often relatively, and FileDownloader alway does its best to speed up the downloading.

#### For FileDownloader, we provide many flexible interfaces to speed up downloading:

1.  If you want the FileDownloadService runs in the main process to reduce I/O by IPC(each callback), configure the `process.non-separate` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).
2. If you think you can accept FileDownloader resume the task which occurred the unknown exception and be interrupted by system or any unknown cases, resume it from earlier length, just feel free to increase the value of `download.min-progress-step` and `download.min-progress-time` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).
3. If you don't concern with the processing of downloading and just care about when each task finish, just use `BaseDownloadTask#setCallbackProgressIgnored()` to reduce processing callback(default 100 times), add also can use `BaseDownloadTask.FinishListener` instead of `FileDownloadListener`.
4. If you don't need FileDownloader to handle the too-frequency callback, just invoke `FileDownloader#disableAvoidDropFrame()`.
5. If you don't need to ensure each callback in the main thread, just invoke `BaseDownloadTask#setSyncCallback(true)`.

etc....

---

In current latest version , FileDownloader depends on okhttp, but In the further version , FileDownloader schedule to support you provide any NET-component which you like.

**Comment by Jacksgong** [comment]
If you have any idea, very welcome contribute or prompt.

**Comment by Jacksgong** [comment]
Have any questions I will reopen this issue, Thanks.

**Comment by Kishankondhiya** [comment]
Hello sir still i am getting low speed sometimes :( i did change in .properties file.
Also i did not getting priority like other downloads if i am downloading one file with two devices and with different downloader so that other downloader getting finish and after it our downloading starts

**Comment by Kishankondhiya** [comment]
I am really glad to implement your downloader in my application but due to some little issue i am getting stuck over there :(

**Comment by Jacksgong** [comment]
Thanks.

If you set `process.non-separate=true`、increase the value of `download.min-progress-step`and `download.min-progress-time`, there is few thing can effect the speed. threre just three threed pools:

1. network-thread-pool
2. launcher-thread-pool
3. callback-message-keep-flow-pools(5 * single-thread-pool)

And for FileDownloader own, we do things as simple as possible for speed up downloading and stability.

---

P.S : For our company's project, we use FileDownloader for parallel downloading some large queues and also used to download individual large resource.  And in our test result,  the downloading speed alwasy almost meet the network-allowed-top-speed (we test in 50Mbps network, and the downloading speed from `BaseDownloadTask#getSpeed` meets 6MB/s).

---

Additions: Some time ago, I have found the okhttp-3.x is slightly slower than okhttp2.4.0(which carried by system as default downloading basic library) in case of downloading. In think there must be more stable and powerful for okhttp-3.x though it result in slightly slower in downloading case. But for more flexible, in following several version I will decoupling with okhttp(#158).

Test okhttp2.4.0 in another branch:

![image](https://cloud.githubusercontent.com/assets/6176417/17726634/e04b6230-6486-11e6-99fe-12d97bdfe9b7.png)

----

Thanks very much for you prompt, When I'm free I will compare those nice open source downloader, And keep study.

---

We will continue to improve this library as much as we can.

**Comment by Kishankondhiya** [comment]
i have change something like this sir,

download.min-progress-step=131072
process.non-separate=true
download.min-progress-time=3000

**Comment by Jacksgong** [comment]
Yes, your configuration is right, through min-progress-time from 2s -> 3s the effect may not be so obvious.

---

> if i am downloading one file with two devices and with different downloader so that other downloader getting finish and after it our downloading starts.

The described remind me one thing: If the FileDownloadService didn't start yet, FileDownloader will try to start the FileDownloadService first and waiting for binding the FileDownloadService when you try to download any task.

Sorry.. If your case is just want to download a single small file, We don't recommend you use our library to handle it, our library too heavy to using for downloading a single small file.
