### ISSUE TITLE
Question about temp file path

### ISSUE THREAD

**Issue by mseroczynski** [lingochamp/FileDownloader#296]
Is it currently possible not to use temp file path?

I've used 0.3.2 (last working version in my app) and tried to update to 1.0.0, but i need my files to stay in particular path while downloading (they meant to be pseudo streamed, played by audio player while downloading). Is it currently possible?

**Comment by Jacksgong** [comment]
FileDownloader has already handled such problem when you upgrade FileDownloader version from  older one which not has temp file path to the newer one which uses temp file path, FileDownloader will convert all downloading task from the target path to the temp path when FileDownloadService launches.

---

- Ref: Check whether the file path successfully converted: [FileDownloadUtils#isFilenameConverted](https://github.com/lingochamp/FileDownloader/blob/80471aa6f43109767efb7364e5061080d14bbee2/library/src/main/java/com/liulishuo/filedownloader/util/FileDownloadUtils.java#L352).

**Comment by mseroczynski** [comment]
My intention is to turn temp file path off - is that possible? I need file to be in place targeted by me **while downloading**.

**Comment by Jacksgong** [comment]
Okey, I know now. FileDownloader doesn't support such feature, sorry.

**Comment by mseroczynski** [comment]
Well then I'll have to fork and modify. Thank you very much for answering :).

Issue can be closed now.

**Comment by Jacksgong** [comment]
Okey, Welcome PR~

**Comment by mseroczynski** [comment]
Are you maybe planning to add this feature now? I'd be really grateful, I've tried to prepare PR but  I've destabilized your library by doing it, does it require much work from you? Thanks!

**Comment by Jacksgong** [comment]
PR is always welcome.

do you mean `My intention is to turn temp file path off - is that possible? I need file to be in place targeted by me while downloading.`?

If this, **It's not easy to turn temp file path off**, if temp file path is off, because of pre-allocate, we have to store all completed download file to the database used for judging whether the task needs to continue to download or has already been completed downloading. ( temp file path simplify this flow).

---

Anyway you can use `FileDownloadUtils#getTempPath(targetPath)` to get the temp file path.

**Comment by mseroczynski** [comment]
Thank you for your response. To be honest I still don't understand what is wrong with theoretically storing metadata of all completed downloads - in my case I'm staying on 0.3.2 because I need consistent location to pseudo-stream *.mp3 file and I would consider such database as you mentioned as no problem at all. Would't simple warning on README be enough?
