### ISSUE TITLE
java.lang.IllegalStateException: Fatal-Exception: You can't bind the FileDownloadService in :filedownloader process.

### ISSUE THREAD

**Issue by yanglichuan** [lingochamp/FileDownloader#314]
java.lang.IllegalStateException: Fatal-Exception: You can't bind the FileDownloadService in :filedownloader process.

**Comment by Jacksgong** [comment]
Occur such exception, because you invoke `FileDownloader#bindService()` in the `:filedownloader` process. This might occur, for example, if you invoke `Filedownloader#bindService()` in your `Application#onCreate` directly without filter the ':filedownlader' process, because FileDownloadService running in the ':filedownloader' process by default, and in this case, `Application#onCreate` will be invoked in the ':filedownloader' process by system.

---

#### Alternative Solution

> You can use any of the following solutions to resolve this problem

1. Invoke `FileDownloader#bindService()` in your `Activity` instead of `Application`
2. Invoke `FileDownloader#bindService()` in `Application#onCreate` but not in  ':filedownloader' process by `!FileDownloadUtils#isDownloaderProcess(Context)`.
3. Set FileDownloadService running in the main process instead of the separate ':filedownloader' process through configurate `process.non-separate=true` in [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).

---

#### Entire message in this Exception: 

```
Fatal-Exception: You can't bind the  FileDownloadService in :filedownloader process.
 It's the invalid operation  and is likely to cause unexpected problems.
 Maybe you want to use non-separate process mode for FileDownloader, More detail about non-separate mode, please move to wiki manually: https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties
```

**Comment by yanglichuan** [comment]
thank you! you are  very helpfull!

**Comment by Jacksgong** [comment]
Okey~
