### ISSUE TITLE
BaseDownloadTask#reuse is called shortly after the call to BaseDownloadTask#pause may raise a exception

### ISSUE THREAD

**Issue by liangnansheng** [lingochamp/FileDownloader#329]
java.lang.IllegalStateException: the messenger is working, can't re-appointment for -756756642@com.liulishuo.filedownloader.DownloadTask@42a72b80

**Comment by Jacksgong** [comment]
你是在哪里调用遇到这个问题的呢？

**Comment by liangnansheng** [comment]
task.reuse();

**Comment by liangnansheng** [comment]
场景就是网络不好的时候，不断点击下载就会出现~

**Comment by Jacksgong** [comment]
在哪里调用`task.reuse();`。是回调里吗？

**Comment by liangnansheng** [comment]
没有出现在回调里

**Comment by Jacksgong** [comment]
`task.reuse()`方法你是在哪里调用的。

这个错误，说明当前任务还在不断的接收回调，无法重新`reuse`，之前有一个版本有修复一个类似的问题(#229)，他这个是在 `completed`/`paused`/`warn`/`error` 这些回调中调用了`trask.reuse()`导致报了上面的错误，后来在0.3.4中修复了。

**Comment by liangnansheng** [comment]
我给他加了一个判断就是if(task.isusing){};后解决了

**Comment by Jacksgong** [comment]
恩。好的。如果觉得报这个异常是不符合预期的，继续评论，我会重新打开这个issue，然后继续跟踪问题。

**Comment by vinaaroncent** [comment]
我出现同样的问题
if (task.getStatus(task.getId(), task.getTargetFilePath()) == FileDownloadStatus.paused) {
     mAExtendPackage.baseDownloadTask.reuse();
     mAExtendPackage.baseDownloadTask.start();
}

**Comment by vinaaroncent** [comment]
写错了。。sorry
if (task.getStatus(task.getId(), task.getTargetFilePath()) == FileDownloadStatus.paused) {
   task.reuse();
   task.start();
}
然后就在task reuse 那里报错了 之前我程序把task pause了

**Comment by Jacksgong** [comment]
@vinaaroncent 可否告知下遇到该问题的FileDownloader的版本。

**Comment by vinaaroncent** [comment]
1.2.2

**Comment by Jacksgong** [comment]
@vinaaroncent 可否告知下`task`是什么类的对象。因为如果是`BaseDownloadTask`是没有`task.getStatus(task.getId(), task.getTargetFilePath())`这样的接口的。只有可能是: `task.getStatus()`。

---

类似问题我重新review了一遍代码，当然你也可以看下报错的源代码。有有可能在任务还在运行之时，进行调用它的`BaseDownloadTask#reuse`才有可能出现对应的异常。

**Comment by vinaaroncent** [comment]
sorry～  我手敲的代码 不是复制的 弄错了。 
之前的 getStatus 是 FileDownloader.getImpl().getStatus
task 是BaseDownloadTask

**Comment by vinaaroncent** [comment]
必复现的流程是：
我在上一个activty的onpause里把task pause了
然后进入下一个activty 在oncreate里判断task是否pause，如果pause 我就reuse start

**Comment by Jacksgong** [comment]
@vinaaroncent 挺奇怪的，FileDownloader并没有与Activity有任何的绑定关系。。可否加下QQ，我给你远程看下吧。我QQ 82780465。加好了回来评论下，我比较少上QQ，然后约定时间。我给你远程定位下问题。

**Comment by vinaaroncent** [comment]
已加～

**Comment by Jacksgong** [comment]
@vinaaroncent 多谢提供的sample project，已经找到原因。

这个问题会在3.0中修复了带上。

#### 原因:

调用`BaseDownloadTask#pause`的时候，并没有同步的进行释放`BaseDownloadTask`的Messenger，因为还有至少一个pause的消息需要通过Messager回调给`BaseDownloadListener`，而默认情况下这个回调并不是同步的，而是放到回调队列中，在排到的时候才抛回主线程的Looper中进行回调。

因此在调用`BaseDownloadTask#pause`之后，立马或者短时间内直接调用`BaseDownloadTask#reuse`，就可能遇到上面的问题。

---

#### Resaon

Calling `BaseDownloadTask#pause` doesn't release the Messenger for the `BaseDownloadTask` object synchronously, since there is at least one `pause` message needs to be called back to the `BaseDownloadListener` via the Messager, and by default, this callback is not synchronized, what is placed in the callback queue waiting for callback in the looper of the main thread.

So in the call `BaseDownloadTask#pause` after called `BaseDownloadTask#reuse` in a short period of time, may raised this exception.

**Comment by B-Esmaili** [comment]
would you mind using english?
