### ISSUE TITLE
File not downloading

### ISSUE THREAD

**Issue by deepinder10** [lingochamp/FileDownloader#342]
I am trying to download files from 
https://savevideos.xyz/download?id=617564696f2659796b6a7065754d4e456b26333230
first there was an exception of size not available and i set http lenient to true in properties now it starts downloading but file is only of 40 bytes while the original size was 9.92 mb
its happening with every link on the above website.

**Comment by Jacksgong** [comment]
The response header I captured in FileDownloadRunnable from your Url: 

```
"date"
"Mon, 03 Oct 2016 13:09:40 GMT"
"content-type"
"text/html; charset=UTF-8"
"set-cookie"
"__cfduid=dfd4856ea374146656364d9d991de17161475500179; expires=Tue, 03-Oct-17 13:09:39 GMT; path=/; domain=.savevideos.xyz; HttpOnly"
"vary"
"Accept-Encoding"
"x-powered-by"
"EasyEngine 3.7.4"
"server"
"cloudflare-nginx"
"cf-ray"
"2ec0a13ccc1e0da3-SJC"
```

This means that there isn't `content-length` filed in response header and either `Transfer-Encoding` also, instead, it looks like a website(`content-type=text/html;charset=UTF-8`).

---

### Why only 40bytes received after set `lenient` to true?

In your case, we can't know the `content-length` from the begining of download, and because you has already set `lenient` to true, so we make it as a [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) to download, in this case, we can't know how much data we need to fetch from the input stream, so we keep fetching the data from the input stream and writing it to the file until there is no data in the stream. That is if the ending file is only 40bytes, the data in the input stream is only 40bytes, and then the end.

In the demo project, there is a chunked-resource testing in SingleTaskTestActivity, what is works well.

---

### Resolution

If you find that the download can be done correctly in other ways, you can compare whether the request headers need to be added, and then you can add the same request headers to FileDownloader to try them out. If you really find FileDownloader has problems in some special cases, very welcome your PR.

**Comment by deepinder10** [comment]
Hi Jacksgong, i tried making the request via Postman and the response headers were these but the issue is the request is taking avg 80-90 seconds.
CF-RAY →2ecb67d97e042deb-BOM
Connection →keep-alive
Content-Disposition →attachment; filename="Coldplay - Hymn For The Weekend (Official video) (savevideos.xyz).mp3"
Content-Length →10400000
Content-Type →application/octet-stream
Date →Tue, 04 Oct 2016 20:32:53 GMT
Server →cloudflare-nginx
X-Powered-By →EasyEngine 3.7.4

**Comment by Jacksgong** [comment]
So... Why different? why the server response two different response header? maybe the reason for the request header?

**Comment by deepinder10** [comment]
I tried to check the request headers on postman but it is taking too much time to respond, maybe some issues.So i tried on Advanced Rest Client
`Date: Fri, 07 Oct 2016 19:19:50 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: EasyEngine 3.7.4
Server: cloudflare-nginx
Cf-Ray: 2ee3b4fb7b342ef3-DEL`

with request headers
`Cookie: __cfduid=de624824f8f138e60b6f468776f60fb311475745126
Source message

GET /download?id=617564696f2659796b6a7065754d4e456b26333230 HTTP/1.1
HOST: savevideos.xyz
cookie: __cfduid=de624824f8f138e60b6f468776f60fb311475745126
`
As i see the tranfer encoding is chunked here, but from your last reply you said 

> so we keep fetching the data from the input stream and writing it to the file until there is no data in the stream. That is if the ending file is only 40bytes, the data in the input stream is only 40bytes, and then the end.

What do you mean by eof, the end of single chunk? as the file or data was of 9.92 mb

**Comment by Jacksgong** [comment]
For that means: You also can check out in [the source code](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L419):

#### If the data is `chunked`:

1. We read data from the input stream.
2. Writing it to the file.
3. Until there is no data in the stream.( so If the ending file is only 40bytes, It must be the data in the input stream is only 40bytes.)

```java
...
...
do{
  // Step 2, read from input stream. (1. We read data from the input stream)
  int byteCount = inputStream.read(buff);
  if (byteCount == -1) {
      // (3. Until there is no data in the stream) ( so If the ending file is only 40bytes, It must be the data in the input stream is only 40bytes.)
      break;
  }

// if (FileDownloadLog.NEED_LOG) {
//     startWriteNanoTime = System.nanoTime();
// }

  // Step 3, writ to file (2. Writing it to the file)
  outputStream.write(buff, 0, byteCount);}
  ...
}
...

```

**Comment by deepinder10** [comment]
you are right that the data might be only 40bytes, i tried downloading it with the google's android download manager and it works perfectly fine and downlaods 9.92 mb

**Comment by Jacksgong** [comment]
I will try to find out the difference with them when I'm free, If you have time, please help me to find it out.

**Comment by Jacksgong** [comment]
The resource Url seems that has already invalidated, any update, I will reopen this issue.
