### ISSUE TITLE
download stops on application exit

### ISSUE THREAD

**Issue by miladz68** [lingochamp/FileDownloader#347]
if the user exits the application by holding down home button and swiping to clear app from memory the download stops and does not get restarted.
I know that the android kills the service and then restarts it. then why doesn't FileDownloader resumes downloading the tasks that were stopped because of service restart ? and all the data is stored in the data base and FileDownloader can restart the download easily. 
I noticed many people have problem with this. If you add this feature it would be great.

**Comment by Jacksgong** [comment]
Thanks, there are some reason and alternative resolution:

1. You can use `FileDownloader#startForeground` to ensure the FileDownloader service not be killed when the user removes your app from the recent apps. [There are some easy ways to use this function](https://github.com/lingochamp/FileDownloader/issues/324#issuecomment-248903937).
2. If the FileDownloader service is killed unexpected but your main process is alive, [FileDownloader will try to restore running tasks to resume them all](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/LostServiceConnectedHandler.java), because FileDownloader knows which task need to restore clearly in the main process.
3. If the FileDownloader service is killed unexpectedly with your main process is also be killed(In your case), FileDownloader doesn't know which tasks need to restore to resume because maybe there are several running task data in the FileDownloader database we can filter out, but there are also some tasks waiting in the FileDownloadList which has already been released when the main process was killed. 


In the current situation, I think it makes sense. If the user wants to kill your app from the recent app, they have already known the downloading will be paused, and when the user re-open your app and re-start download, all tasks will be resumed from the breakpoint, what meet user-expected.

**Comment by miladz68** [comment]
thank you for your answer.
I think for case 3 that you mentioned, FileDownloader can save the state of each task to database and use this information to resume tasks when service restarts.

**Comment by Jacksgong** [comment]
Sorry, The FileDownloader database in the internal architecture is only used to store some data used for resuming from the breakpoint, we want it as light as possible.

If FileDownloader database stores each task once you enqueue to FileDownloader:

1. The FileDownloader database will become very heavy to now.
2. We need to maintain every situation of 

That is absolutely beyond the origin aim of FileDownloader want.

---

## Most important reasons:

This isn't the most case.

1. For Android, If the user wants to kill your app from the recent app, they want your app can be in control to be killed. If we still to resume tasks, that out of control for your users, that not make sense, we recommend you: please don't do that to harm your users.
2. If you want to let your user know your downloading will continue even if they kill your app from the recent app, you can use `FileDownloader#startForeground`, which makes sense.

**Comment by Jacksgong** [comment]
Thanks for your agreement, I've just got one further point: If there is only the FileDownloader process alive and resume tasks automatically, you also don't know any download information.
