### ISSUE TITLE
Accept DocumentFile to support direct download to External SD Card

### ISSUE THREAD

**Issue by jordyamc** [lingochamp/FileDownloader#349]
To write directly to the SD Card on Android 6+ we have to use the Access Framework, but it changes the File to DocumentFile, can you add the option to pass a custom DocumentFile, or instead the outputStream from the DocumentFile?

**Comment by metalurgus** [comment]
I face the same problem. But here are few things to note:

1. This issue is about physical removable memory card, like microSD, which is inserted into a phone (android device), not about the emulated SD card, which is a part of phone's built-in memory.
2. Issue comes on Android 4.4 devices and up (in API 19 google restricted direct access to memory cards.), not from Android 6
3. For my oppinion, acceptable destenation type for the download can be `Uri`, which can be created from `File`, from `DocumentFile`. So it would be grait to replace or just add `setPath(String path)` with `setUri(Uri uri)` in `BaseDownloadTask`.

I've tried to do it myself, but the library source code is too complex for me.

Here is how to open `OutputStream` from `Uri`:    
```
Uri uri = ...;
ParcelFileDescriptor pfd = context.getContentResolver().openFileDescriptor(uri, "w");
FileOutputStream fileOutputStream = new FileOutputStream(pfd.getFileDescriptor());
```

**Comment by jordyamc** [comment]
I have no issues with SD in Api 19

I did that method in one part of my app, but the FileDescriptor closes while writing, i found other method to do the transfer:

```
Uri uri = ...;
OutputStream outputstream=getContentResolver().openOutputStream(uri, "rw");
```

**Comment by Jacksgong** [comment]
Sorry for my missed this issue, this is very significant.

**Comment by davetao** [comment]
Did anyone manage to have a workaround while this feature is being developed? I tried creating a class that implements `FileDownloadOutputStream` but that  only takes in a `File` in the Creator constructor

**Comment by Jacksgong** [comment]
Sorry guys, I will handle this in the next version.

**Comment by futurexiong** [comment]
Any plan to release 1.4.2?

**Comment by Jacksgong** [comment]
Sorry for delay, I tried to write code to support this feature, but it's not free time enough time for me, so all processing is intercepted.

On the 1.5.3, it will be implemented with:

1. implement Uri OutputStream
2. change the `.temp` file mechanism to `.lock` file mechanism, which is means we no longer using the `temp` file since we have no access permissoin to its `.temp` file, and we store its `.lock` file to the application folder and make mapping to the target file path if the `.lock` file is exist the file is not completed downloading, so we can feel free to pre-allocate for the target file with write data to the target file directlly.
3. The old `.temp` file migration: I will try  to migrate the `.temp` file, but if there isn't permission to access the old `.temp` file, it will be discard directlly.

---

Above is the imagine plan, any advice for this feature is open... please comment and let me know.

**Comment by Jeffin21** [comment]
Please do this. :+1:

**Comment by saipsa** [comment]
@Jacksgong When can we expect this ? Thank you for amazing library

**Comment by Jacksgong** [comment]
This issue has been solved on [okdownload](https://github.com/lingochamp/okdownload)
