### ISSUE TITLE
FileDownloader stops download files after the application is closed!

### ISSUE THREAD

**Issue by lap089** [lingochamp/FileDownloader#37]
Even though the filedownloader process is still alive, it stops download right after i kill my application (swipe to close app).

**Comment by changjiashuai** [comment]
error()-629675092, msg=fstat failed: ENOENT (No such file or directory)

**Comment by Jacksgong** [comment]
If you kill your application with 'swipe to close app',  the filedownloader process will be killed by the system with the main process.  But you saw it was still alive, because the system has relaunched the filedownloader process immediately ( because we use `Service.START_STICKY` in `FileDownloadService#onStartCommand`).

> ps, If your main process has been killed by the system(not by swipe to close app manually), if the filedownloader process is still alive, it will continue to download files until the completion of all or killed by system( http://developer.android.com/guide/components/processes-and-threads.html )

**Comment by lap089** [comment]
You're right, but when I switch to another application and turn off the screen, the main app is killed and the download process is stopped too! I don't understand why

**Comment by Jacksgong** [comment]
> You can cover all low memory cases by [T-Spoon/Android-Developer-Toolbelt](https://github.com/T-Spoon/Android-Developer-Toolbelt)

Sorry, It would be split into two cases:

#### CASE 1. Parallel Download

If you start the parallel download, all tasks would be pushed to the filedownloader process, so there are all tasks in the filedownloader process already.  

- when the main process has been killed by System, but the filedownloader process is still alive,  it will continue to download files until the completion of all, **but if your system's memory is too low, the filedownloader process would be killed by System too**([RULES](http://developer.android.com/guide/components/processes-and-threads.html).

#### CASE 2.  Serial Download

If you start the serial download, tasks would be pushed to the filedownloader process one by one, there is only one running task in the filedownloader process. 

In this case, when your main process has been killed by System, though the filedownloader process is still alive, It will just download the currently running task, and can't continue.

**Comment by lap089** [comment]
Ok, I understand now! 
but when I download files serially, are all of the information of the files stored on the database of filedownloader or the database only stores the running one?
Could you please show me a way to retrieve those files?

**Comment by Jacksgong** [comment]
First of all, the task what was pushed to the filedownloader process would be stored in the database of filedownloader only. 

And the filedownloader database is used for resuming the task from its break-point or checking the downloaded file to conclude out the downloaded file is match the information in the database.

---

If you want to 'retrieve those files':

If you can restart all those tasks, just start the same tasks queue feel free, FileDownloader will call-back `complete` immediately if the task has already downloaded and resume the not-finished-task from its break-point automatically. 

If you need to store the information of your task for your requirements, recommend maintaining the database by yourselves. ( Recommended reference: [TaskManagerDemo](https://github.com/lingochamp/FileDownloader/blob/master/demo/src/main/java/com/liulishuo/filedownloader/demo/TasksManagerDemoActivity.java))

**Comment by Jacksgong** [comment]
#110

**Comment by YuriHeupa** [comment]
@Jacksgong You said in case 2 to push tasks one by one, but is there any method to push tasks while the download queue is already started?

The reason is I want to have a download queue that download tasks one by one, but I need to push tasks while the queue have been already started, and if the app get restarted, all previously queued downloads need to restart in the same order as they were added before. I didn't find this in any example, either in wiki.

What I already did was define a listener for all tasks, then create using this:
```java
FileDownloader.getImpl().create(model.getDownloadUrl())
                .setPath(model.getFilePath())
                .setAutoRetryTimes(1)
                .setListener(downloadListener)
                .setTag(model)
                .ready();
```

And right before the task creation I call this:

```java
FileDownloader.getImpl().start(downloadListener, true);
```

But the second download task gives me this error:
`java.lang.IllegalStateException: This task is running -951383063, if you want to start the same task, please create a new one by FileDownloader.create`

I'm missing something?

**Comment by Jacksgong** [comment]
First of all, Occur such exception `java.lang.IllegalStateException: This task is running -951383063, if you want to start the same task, please create a new one by FileDownloader.create`, because the task object you requested to start already started and running. It must be encountered in case of you hold the running task object and restart it manually, this is not acceptable, because it is running and in the running flow, but instead, you can create new one with same URL and same SavePath and start it, but if there is the same task(same URL and same SavePath) before is running, you will receive a `FileDownloadListener#warn` because it is not as expected to download 2 task with same URL and same Path meanwhile. So in your case, please consider wrap your own ListenerManager and just register a new listener, instead of starting the same task, Ref #103 .

---

> want to have a download queue that downloads tasks one by one, but I need to push tasks while the queue has been already started, and if the app gets restarted, all previously queued downloads need to restart in the same order as they were added before.

## Follow your requirement:

##### I assume you need your download queue continue to run even your App back to the background, and if the user back to your App, you need to regain the listener of download queue and if your App process was killed, you need to restart the download queue.

#### The solution:

> It you want to one by one, just FileDownloader.getImpl().start(downloadListener, true).

You need your own ListenerManager for your requirement because your listener does not follow your Activity's lifecycle, it follow your App-process lifecycle, so you can **regain the listener of download queue** similar to #103 ( Wrap the Manager to hold the listener). And if you can't find any completed or any running tasks in your Manager, it must be your App process was killed and the user restarted your App, in this situation, **you just restart the queue as the fist time without need to worry the task in the queue which has downloaded which did not download**, because if the task has downloaded the FileDownloader will pass it automatically.

**Comment by YuriHeupa** [comment]
@Jacksgong Thank you for the nice explanatory answer! I've wrapped the manager like you said, it's working perfectly for handling events.

The only thing that I didn't found a good approach is making a queue that downloads files one at a time, I'll try to explain detailed in a simple example:

I've 2 Files to download, fileA and fileB, I can start a download for fileA in this way:
```java
FileDownloader.getImpl().create(fileA.getUrl())
        .setPath(fileA.getPath())
        .setListener(commonLis)
        .start();
```
*The `commonLis` is hold by the manager.
If I call this snippet again for fileB while fileA is downloading, an 2nd download will start in parallel, which I want to be queued and started right after fileA completion (or any event that stop downloading). 

In this example I've used only 2 files, but in real application it would be hundreds of files in queue.

I'm looking if there's any way using this library to queue and handle this automatically, or I need to do this manually holding references to files and pop each one for download right after receiving an interruption event?

**Comment by tapow** [comment]
> @Jacksgong Thank you for the nice explanatory answer! I've wrapped the manager like you said, it's working perfectly for handling events.
> 
> The only thing that I didn't found a good approach is making a queue that downloads files one at a time, I'll try to explain detailed in a simple example:
> 
> I've 2 Files to download, fileA and fileB, I can start a download for fileA in this way:
> 
> ```java
> FileDownloader.getImpl().create(fileA.getUrl())
>         .setPath(fileA.getPath())
>         .setListener(commonLis)
>         .start();
> ```
> 
> *The `commonLis` is hold by the manager.
> If I call this snippet again for fileB while fileA is downloading, an 2nd download will start in parallel, which I want to be queued and started right after fileA completion (or any event that stop downloading).
> 
> In this example I've used only 2 files, but in real application it would be hundreds of files in queue.
> 
> I'm looking if there's any way using this library to queue and handle this automatically, or I need to do this manually holding references to files and pop each one for download right after receiving an interruption event?

Hi YuriHeupa,

I am also facing the same issue. Can you please tell me how u handle this problem.

In real App, I am downloading >100 files but the receiving response and received file are not in the same sequence.

Please advice..?
