### ISSUE TITLE
java.lang.RuntimeException: sofar[4713507] not equal total[4709411]

### ISSUE THREAD

**Issue by valmeeki001** [lingochamp/FileDownloader#379]
got this exception when the download is about to finish.

```
W/System.err: java.lang.RuntimeException: sofar[4713507] not equal total[4709411]
    at (FileDownloadRunnable.java:484)
```

**Comment by Jacksgong** [comment]
Occur such exception, because the value of 'content-length' inside the Response-Header  is not equal to the real length in the input-stream from the back-end.

**Comment by valmeeki001** [comment]
sir, is there any way to ignore this error and continue the download?

**Comment by Jacksgong** [comment]
For simple way, you can ignore this error by yourself, because when you get the `FileDownloader#error` callback with this error message, FileDownloader has already completed fetch all data from the network input stream, and FileDownloader will not delete the downloaded file. **So if you receive this error message in `error` callback, you just do some completed thing you want in it**.
