### ISSUE TITLE
How to get list of al downloading andl downloaded items.

### ISSUE THREAD

**Issue by shivam21** [lingochamp/FileDownloader#388]

**Comment by Jacksgong** [comment]
#### downloaded items

For more light weight, FileDownloader doesn't maintain the downloaded items, when task is completed download, FileDownloader will delete all its data from FileDownloader for keep FileDownloader Lighter.

If you need this information, you need to maintain it by yourself. 

But FileDownloader provide the method to help you perfect it: `FileDownloader#getStatus`, so you can use this method to make sure whether the `task id & file path` you know is completed download.

#### downloading items

FileDownloader doesn't provide any method to get downloading items, because the list is very variable.

For this feature, if you have this requests, we really recommend you to wrap your own [DownloadManager](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124), or maintain data such `TasksManagerDemoActivity` in demo project.
