### ISSUE TITLE
 W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false

### ISSUE THREAD

**Issue by xoex** [lingochamp/FileDownloader#398]
Hi.
I got two problems with downloading. To keep questions separate I ask first one here,
 I got a lot of this debug message :

```
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer 3, but is contains false
W/FileDownloader.MessageSnapshotGate: callback event transfer -3, but is contains false
```
What is this?

**Comment by Jacksgong** [comment]
> Sorry for the non-make-sense log wording, I will correct this log.

### Cause

Raise this log, because the internal framework callback a event, but in the upper layer there isn't any running task, so this event can't be consumed.

### Worry?

Please don't worry about this log, because there are several normal cases will raise this log.

### Enhance

- I will correct this log.
- Alternate this log level to Debug.
