### ISSUE TITLE
How to get the new url after 302 redirect happening.

### ISSUE THREAD

**Issue by hufozhu** [lingochamp/FileDownloader#415]
Hi,

Recently, we get a lot of broken files after downloaded, so we want to check if the download urls are redirected and record the true download url when we get a broken file. Any idea about how to implement this? Thanks very much.

**Comment by Jacksgong** [comment]
In the old version(before v1.3.9), the redirect have been handled by okHttp(we will use the final url to fetch data-stream after redirect).

**But in the latest version**, since FileDownloader no longer dependent the okHttp, and the default connection component is `FileDownloadUrlConnection` which just use `URL#openConnection`, it doesn't handle redirect-state.

So in the current latest version, you can wrap your own `FileDownloadConnection` to handle redirect by yourself, please move to [the doc](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component).

**Comment by Jacksgong** [comment]
If you want to the FileDownloader use okHttp like before v1.3.9, just use [this repo](https://github.com/Jacksgong/filedownloader-okhttp3-connection) or write your own `FileDownloadConnection` component.
