### ISSUE TITLE
Why "FileDownloadList" is empty after close app and open it again?

### ISSUE THREAD

**Issue by SAFatemi** [lingochamp/FileDownloader#427]
Salam.
Thank you for develop and share this good library.
I use your library and want to continue downloads within service that show progress of downloads in one custom notification that shown count of downloading, paused or pending items.
I have a problem with `FileDownloadList` that is after close app and open it again, `FileDownloadList` is completely reset and not contains any item!

**Comment by SAFatemi** [comment]
@Jacksgong

**Comment by Jacksgong** [comment]
First of all, I think [this post](https://github.com/lingochamp/FileDownloader/wiki/Low-Memory%3F) may be helpful to you to understand why.

---

The  `FileDownloadList` is used in internal, what is just used for caching some running tasks, but it is not exactly right since once its host process is killed by the system, all data is missing on it, but meanwhile all tasks are running in the `:filedownloader` process will not be impacted. After the user relaunch the host process we will not sync the tasks from `:filedownloader` process to the host process manually, but if you start all tasks as before you will receive callbacks from now on, as what has been explained in [the Low Memory? post](https://github.com/lingochamp/FileDownloader/wiki/Low-Memory%3F).

**Comment by Jacksgong** [comment]
So we don't recommend you to use it. You can wrap [you own manager](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124), if so you can know how it going on clearly rather than use `FileDownloadList` what just is created for internal logic.
