### ISSUE TITLE
File downloaded has cleaned by Clean Master

### ISSUE THREAD

**Issue by sinhpn92** [lingochamp/FileDownloader#463]
I used FileDownloader to download file and save to default root path. However, when i used Clean Master app to clean junk file, my file has cleaned after i run clean by Clean Master. What's wrong here? Please help me...

**Comment by Jacksgong** [comment]
It is because the default root path used for saving download file is the application's external cache folder: `Context#getExternalCacheDir()`:

```java
public static String getDefaultSaveRootPath() {
    if (!TextUtils.isEmpty(DEFAULT_SAVE_ROOT_PATH)) {
        return DEFAULT_SAVE_ROOT_PATH;
    }

    if (FileDownloadHelper.getAppContext().getExternalCacheDir() == null) {
        return Environment.getDownloadCacheDirectory().getAbsolutePath();
    } else {
        //noinspection ConstantConditions
        return FileDownloadHelper.getAppContext().getExternalCacheDir().getAbsolutePath();
    }
}
```

---

If you dont' want your default root path isn't the application's external folder, just custmoize it through `FileDownloadutils.setDefaultSaveRootPath(path)` manually.
