### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by congwiny** [lingochamp/FileDownloader#473]
使用FileDownloadQueueSet批量下载文件时，某个task下载到一定进度，比如80%然后就下载失败了，显示以下错误，是什么问题呀
javax.net.ssl.SSLException: Read error: ssl=0x9b94e000: I/O error during system call, Connection reset by peer

**Comment by congwiny** [comment]
添加这句代码会解决这个问题吗？
downloadTask.setAutoRetryTimes(10);

**Comment by Jacksgong** [comment]
这个是网络问题，重试在有些情况下可以解决，但是并不是有效的方法。

**Comment by Trinkes** [comment]
Can you speak in English? I some "Connection reset by peer" errors too, but it's a SocketException.

**Comment by Jacksgong** [comment]
@Trinkes Okay, It's the TCP layer fatal error, refer: [here](http://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean)


#### Reason

If you occur this exception, it means the backend close your connection unusual. 

#### Solution

- You can optimize the TCP protocol connection to handle this problem through customizing your own `FileDownloadConnection` component, Ref [here](https://github.com/lingochamp/FileDownloader/wiki/Open-Customized-Component)
- Maybe you can retry connect several times through setting `BaseDownloadTask#setAutoRetryTimes` because of occurring this exception maybe because of the backend server was crashed.
