### ISSUE TITLE
Keep the listener after exiting from Application

### ISSUE THREAD

**Issue by MurtadhaS** [lingochamp/FileDownloader#540]
Hi,
After using:
`FileDownloader.getImpl().create(URL)
        .setPath(path)
        .setCallbackProgressTimes(100)
        .setListener(TasksManager.getImpl().taskDownloadListener)
        .setTag(videoModel.getNb());`
I want the **taskDownloadListener** to persist after I exit the application using **back button**, because in that case the **FileDownloader** keeps running on background without the listener being attached to it .!

**Comment by Jacksgong** [comment]
Sorry, I can't get what's problem you occurred, because FileDownloader will not unattached `taskDownloadListener` manually even if you using `back button` to exist the application. 

the only case you can't get process when FileDownloader keeps running is the main process is killed by system, and about this case, please ref to [Low memory](https://github.com/lingochamp/FileDownloader/wiki/Low-Memory%3F).
