### ISSUE TITLE
checksum

### ISSUE THREAD

**Issue by mina-william** [lingochamp/FileDownloader#550]
Hi
Thank you for this library,  I wan't to ask about how to add checksum (ex: SHA1) to the file downloading task to verify Integrity of files.
is there is any way to add extra check for the checksum to determine if the file has been successfully downloaded instead of just check the file size.
thanks.

**Comment by Jacksgong** [comment]
It's very recommended using checksum(ex: SHA1) as the Etag, so you can get it since `connect` callback, and check it on the `blockComplete` and if the check failed you can throw any `Throwable` to block `completed` callback on `blockComplete`.

---

by the way, FileDownloader has already checked the size between `content-length` and fetched-size on the end on the internal.

---

Any other detail suggestion or PR is welcome!
