### ISSUE TITLE
download in background

### ISSUE THREAD

**Issue by vd92** [lingochamp/FileDownloader#578]
First of all thanks for this magical library
my app is download based and some files have heavy size and it is the resaon I want to download file's in background not main process but I didn't find any solution to get this . Can you please guide me?

**Comment by Jacksgong** [comment]
As the default, the FileDownloadService is running on the `:filedownloader` process rather than the main process, so if you want, it has already done as default. 

Otherwise, If you want to control such Switcher, just ref [here](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)
