### ISSUE TITLE
Is there any reason why FileDownloadMgr, DefaultDatabaseImpl, DefaultDatabaseOpenHelper are not public?

### ISSUE THREAD

**Issue by hocinehamdi** [lingochamp/FileDownloader#585]
The fact that they are not public they can't be used in an app that has FileDownloader as a dependancy.

**Comment by Jacksgong** [comment]
Because it's very dangerous to do that. 

When I write code for such Classes, I never consider the case of that, it can raise many fatal problems for you to use FileDownloader when you do that.

---

If there are problems on there, VERY WELCOME PR.
If you think it can be more flexible, VERY WELCOME PR.

---

Sweet Tips: You can customize your own components on FileDownloader, ref: https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component
