### ISSUE TITLE
carry response header through `connect` callback

### ISSUE THREAD

**Issue by EMIN3M1986** [lingochamp/FileDownloader#586]
Hi. how can I  get Content-Disposition and Content-type of an url before download ? 
Now I use this code:
```
                URL url = new URL(item.URL);
                HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("HEAD");
                connection.connect();
                String contentType = connection.getContentType();
                String contentDisposition = connection.getHeaderField("Content-Disposition");
```

**Comment by Jacksgong** [comment]
I know what you want, but the current version we have not yet supported return the response header to the up layer because for the most user they don't need such object and transfer the response header is a little heavy.

But for the current version, you also can get the response header through customizing your own connection component, ref: https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component

---

BUT I have another point to support this feature very light, on the later version, I will support carry response header through `connect` callback.

**Comment by Jacksgong** [comment]
This has been implemented on [okdownload](https://github.com/lingochamp/okdownload).
