### ISSUE TITLE
Can't download large files.

### ISSUE THREAD

**Issue by dmitrybudyak** [lingochamp/FileDownloader#600]
Hi,

your lib looks amazing, thank you. 

But currently I need availability to download some large media files (~5GB) and It is not worked for me in both situations where allocation is enabled and disabled. It is possible to download large files now? Thank you.

Note: files tried to download to sd card, checked on ~10MB write speed.

If allocation is enabled:
https://gist.github.com/dbudyak/54d6d9485bc4d227f16101dce54355a2

If allocation is disabled (and added.outputStreamCreator(new FileDownloadBufferedOutputStream.Creator())) I still see "Can't support 'seek' in BufferedOutputStream." error, independed on file size.

**Comment by Jacksgong** [comment]
Absolutely, we support download any size file, and only need to notice is when the file is larger than 1.99G, you need to use `getLargeFileSoFarBytes()` and `getLargeFileTotalBytes()`.

---

P.S. If you want to disable pre-allocation just add `file.non-pre-allocation=false` on the [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties).

---

So, I see your crash stack, the problem is `java.io.SyncFailedException: fsync failed: EBADF (Bad file descriptor)` , then:

1. could you please tell me how many bytes of data have been downloaded before raising this error? 2. could you give me your Url to let me reproduce such error?

**Comment by dbudyak** [comment]
This is more detailed [cut of log](https://gist.github.com/dbudyak/74e9b2bd394bc2976b428ac556394445) in case if I set `file.non-pre-allocation=false`. I see allocation for file in storage with expected size (size of file on server), but I didn't find size for already downloaded bytes. I watch to Network Profilier in new Android Studio 3.0 and see that download not stopped, it is continued some more time with downloading packets about ~20MB and logcat full of `SyncFailedException` exceptions.

Url to our production binary data: http://pre-cdp.playfamily.ru/data/storage13/pr/db59bd16-9849-40ce-9f7b-5fc173317b6e/output.ism/Manifest.mpd/offline?data

Also I test [another url](http://speedtest.tele2.net/10GB.zip) and I've got `java.io.IOException: ftruncate failed: EFBIG (File too large)`

And if I use [other production url](http://cdp.playfamily.ru/data/storage14/pr/af56e17f-5dd1-4b63-a174-c8ebc5d8face/output.ism/Manifest.mpd/offline?data) to file with less size then download is successfully complete.


If I try to set `file.non-pre-allocation=true` then downloading of any file not started with `java.lang.IllegalAccessException: Can't support 'seek' in BufferedOutputStream.` (`.outputStreamCreator(new FileDownloadBufferedOutputStream.Creator())` is already added in library init method as [described in your wiki](https://github.com/lingochamp/FileDownloader/wiki/Optimize-Tutorial))

**Comment by Jacksgong** [comment]
sorry for my mistake,  If you want to disable pre-allocation just add **`file.non-pre-allocation=true` ** on the filedownloader.properties.

**Comment by yannanzheng** [comment]
Can't download a large file about 3.8G

**Comment by rantianhua** [comment]
Long time no response.
