### ISSUE TITLE
Large file download error when pause and resume !!

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#682]
Exception :java.net.SocketException: Connection failed with code[416] on task[1421067462], which is changed after verify connection, so please try again.

**Comment by Jacksgong** [comment]
the wrong range for the large file is fixed on [1.6.2](https://github.com/lingochamp/FileDownloader/releases/tag/v1.6.2).

---

If you are using v1.6.2 and still meet such exception, the reason is described on the exception message:

```
Connection failed with code[416] on task[1421067462], which is changed after verify connection, so please try again.
```

If you try again and still download error with this problem, you can fix this problem with following ways:

1. please ask your backend partner: why response code is 416 with the right range(what is generated through the very connection which is provided refer to the first backend response header).
2. disable the multi-connection download for this problem url, which relates to [`ConnectionCountAdapter`](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)
