### ISSUE TITLE
下载出现416错误

### ISSUE THREAD

**Issue by ZY9898** [lingochamp/FileDownloader#737]
从又拍云服务器下载zip压缩包的时候，始终报416错误，无法下载，用原生httpURLconnection下载没问题

**Comment by Jacksgong** [comment]
1. 打开日志: `FileDownloadLog.NEED_LOG=true`
2. 贴出`:filedownloader`进程与主进程的Logcat。

**Comment by ZY9898** [comment]
~~~callback -1125231275 old[3] new[-1] 1
08-21 11:39:39.326 18593-19860/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify error -1125231275@com.liulishuo.filedownloader.DownloadTask@26f8d258 java.net.SocketException: Connection failed with code[416] on task[-1125231275], which is changed after verify connection, so please try again.
08-21 11:39:39.326 18593-19860/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@53f9c22 by -1

**Comment by ZY9898** [comment]
这样的log可以不？

**Comment by Jacksgong** [comment]
这样定位不了问题的，416是服务端返回的，含义是`Range Not Satisfiable`，但是按照本地的代码来说Range计算应该是没有问题的，所以这边需要输出我上面提到的日志，看到我们这边给过去的range是多少，为什么无法满足？是否是本地真的计算错误，还是服务端的问题。然后再给出进一步解决方案。

**Comment by ZY9898** [comment]
这个日志么？
08-21 12:57:00.896 12308-12322/com.liulishuo.filedownloader.demo I/art: Debugger is no longer active
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTask: setTag 1
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTask: setListener com.liulishuo.filedownloader.demo.HybridTestActivity$3@317b6cb4
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.InQueueTaskImpl: add the task[0] to the queue
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.FileDownloadList: add list in all 0@com.liulishuo.filedownloader.DownloadTask@33e450dd 0 1
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo D/GlobalMonitor: on request start 1 TRUE
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.FileDownloader: start list attachKey[830172340] size[1] listener[com.liulishuo.filedownloader.demo.HybridTestActivity$3@317b6cb4] isSerial[FALSE]
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: call start Url[https://cdn.hlhdj.cn/photos/2017/08/16/b8b95e70-96a0-450e-9464-665f22d81f8c.zip], Path[null] Listener[com.liulishuo.filedownloader.demo.HybridTestActivity$3@317b6cb4], Tag[1]
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTask: setPath /storage/emulated/0/Android/data/com.liulishuo.filedownloader.demo/cache/57994e3587f7605c9d46186d41fb61a2
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTaskHunter: save Path is null to /storage/emulated/0/Android/data/com.liulishuo.filedownloader.demo/cache/57994e3587f7605c9d46186d41fb61a2
08-21 12:57:05.686 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: the task[-1125231275] has been into the launch pool.
08-21 12:57:05.686 12308-17244/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify begin -1125231275@com.liulishuo.filedownloader.DownloadTask@33e450dd
08-21 12:57:05.686 12308-17244/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@1b003323 by 11 
08-21 12:57:05.706 12308-17247/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[11] new[1] 1
08-21 12:57:05.706 12308-17247/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify pending -1125231275@com.liulishuo.filedownloader.DownloadTask@33e450dd
08-21 12:57:05.706 12308-17247/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[1] new[6] 1
08-21 12:57:05.706 12308-17247/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify started -1125231275@com.liulishuo.filedownloader.DownloadTask@33e450dd
08-21 12:57:05.846 12308-17247/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[6] new[-1] 1
08-21 12:57:05.846 12308-17247/com.liulishuo.filedownloader.demo V/FileDownloader.FileDownloadList: remove -1125231275@com.liulishuo.filedownloader.DownloadTask@33e450dd left -1 0
08-21 12:57:05.846 12308-17247/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify error -1125231275@com.liulishuo.filedownloader.DownloadTask@33e450dd com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 416, 
                                                                                                          request headers: {If-Match=["9de081cebbb589b401b1cd64278aaaa8"], Range=[bytes=20480-]} 
                                                                                                          response headers: {null=[HTTP/1.1 416 Requested Range Not Satisfiable], Cache-Control=[no-store], Connection=[keep-alive], Content-Language=[en], Content-Length=[207], Content-Type=[text/html; charset=utf-8], Date=[Mon, 21 Aug 2017 04:57:05 GMT], Server=[marco/1.6], Via=[T.118131.R.1, M.ctn-sc-mei-132], X-Android-Received-Millis=[1503291425824], X-Android-Response-Source=[NETWORK 416], X-Android-Sent-Millis=[1503291425808], X-Request-Id=[9835e24e428ea432ee41040b6e087a32]}
08-21 12:57:05.846 12308-17247/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@1b003323 by -1 
08-21 12:57:06.456 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadInfoDiff: Thread count = 19. Thread differ : +2. FlowSingle: +1 [(+)FileDownloader-Flow-03] | LauncherTask: +1 [(+)FileDownloader-LauncherTask5]
08-21 12:57:06.456 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSizeDiff: Thread count = 19. Thread differ : +2. FlowSingle: +1 | LauncherTask: +1
08-21 12:57:06.466 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSize: Thread count = 19. Binder: 3 | FlowSingle: 1 | LauncherTask: 1 | unknown: 14
08-21 12:57:12.486 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadInfoDiff: Thread count = 17. Thread differ : -2. FlowSingle: -1 [(-)FileDownloader-Flow-03] | LauncherTask: -1 [(-)FileDownloader-LauncherTask5]
08-21 12:57:12.486 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSizeDiff: Thread count = 17. Thread differ : -2. FlowSingle: -1 | LauncherTask: -1
08-21 12:57:12.486 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSize: Thread count = 17. Binder: 3 | unknown: 14

**Comment by Jacksgong** [comment]
这个是主进程的，提供下下载进程的日志。

**Comment by ZY9898** [comment]
哇，大佬，是这个不？
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTask: setTag 1
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTask: setListener com.liulishuo.filedownloader.demo.HybridTestActivity$3@1b26a8fe
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.InQueueTaskImpl: add the task[0] to the queue
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.FileDownloadList: add list in all 0@com.liulishuo.filedownloader.DownloadTask@967885f 0 1
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo D/GlobalMonitor: on request start 1 TRUE
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.FileDownloader: start list attachKey[455518462] size[1] listener[com.liulishuo.filedownloader.demo.HybridTestActivity$3@1b26a8fe] isSerial[FALSE]
08-21 14:03:20.636 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: call start Url[https://cdn.hlhdj.cn/photos/2017/08/16/b8b95e70-96a0-450e-9464-665f22d81f8c.zip], Path[null] Listener[com.liulishuo.filedownloader.demo.HybridTestActivity$3@1b26a8fe], Tag[1]
08-21 14:03:20.646 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTask: setPath /storage/emulated/0/Android/data/com.liulishuo.filedownloader.demo/cache/57994e3587f7605c9d46186d41fb61a2
08-21 14:03:20.646 12308-12308/com.liulishuo.filedownloader.demo D/FileDownloader.DownloadTaskHunter: save Path is null to /storage/emulated/0/Android/data/com.liulishuo.filedownloader.demo/cache/57994e3587f7605c9d46186d41fb61a2
08-21 14:03:20.646 12308-12308/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: the task[-1125231275] has been into the launch pool.
08-21 14:03:20.646 12308-20438/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify begin -1125231275@com.liulishuo.filedownloader.DownloadTask@967885f
08-21 14:03:20.646 12308-20438/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@17a2b75 by 11 
08-21 14:03:20.666 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[11] new[1] 1
08-21 14:03:20.666 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify pending -1125231275@com.liulishuo.filedownloader.DownloadTask@967885f
08-21 14:03:20.666 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[1] new[6] 1
08-21 14:03:20.666 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify started -1125231275@com.liulishuo.filedownloader.DownloadTask@967885f
08-21 14:03:20.776 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[6] new[2] 1
08-21 14:03:20.776 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify connected -1125231275@com.liulishuo.filedownloader.DownloadTask@967885f
08-21 14:03:20.986 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.MessageSnapshotGate: ~~~callback -1125231275 old[2] new[-1] 1
08-21 14:03:20.986 12308-20445/com.liulishuo.filedownloader.demo V/FileDownloader.FileDownloadList: remove -1125231275@com.liulishuo.filedownloader.DownloadTask@967885f left -1 0
08-21 14:03:20.986 12308-20445/com.liulishuo.filedownloader.demo D/FileDownloader.FileDownloadMessenger: notify error -1125231275@com.liulishuo.filedownloader.DownloadTask@967885f java.net.SocketException: Connection failed with code[416] on task[-1125231275], which is changed after verify connection, so please try again.
08-21 14:03:20.986 12308-20445/com.liulishuo.filedownloader.demo V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@17a2b75 by -1 
08-21 14:03:21.566 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadInfoDiff: Thread count = 19. Thread differ : +2. FlowSingle: +1 [(+)FileDownloader-Flow-05] | LauncherTask: +1 [(+)FileDownloader-LauncherTask7]
08-21 14:03:21.566 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSizeDiff: Thread count = 19. Thread differ : +2. FlowSingle: +1 | LauncherTask: +1
08-21 14:03:21.566 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSize: Thread count = 19. Binder: 3 | FlowSingle: 1 | LauncherTask: 1 | unknown: 14
08-21 14:03:27.586 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadInfoDiff: Thread count = 17. Thread differ : -2. FlowSingle: -1 [(-)FileDownloader-Flow-05] | LauncherTask: -1 [(-)FileDownloader-LauncherTask7]
08-21 14:03:27.586 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSizeDiff: Thread count = 17. Thread differ : -2. FlowSingle: -1 | LauncherTask: -1
08-21 14:03:27.586 12308-12398/com.liulishuo.filedownloader.demo D/FileDownloadApplication: drawUpEachThreadSize: Thread count = 17. Binder: 3 | unknown: 14

**Comment by like001** [comment]
大神，我这边下载一个大的apk文件，也报这个错误416。我并没有新开进程去下载。
贴出:filedownloader的log如下：
08-21 15:30:53.206 19375-19439/mytag V/FileDownloader.FileDownloadList: remove 235412632@com.liulishuo.filedownloader.DownloadTask@2f0dffa left -3 0
08-21 15:30:53.206 19375-19439/mytag D/FileDownloader.FileDownloadMessenger: notify block completed 235412632@com.liulishuo.filedownloader.DownloadTask@2f0dffa FileDownloader-LauncherTask2
08-21 15:30:53.209 19375-19439/mytag D/FileDownloader.FileDownloadMessenger: notify completed 235412632@com.liulishuo.filedownloader.DownloadTask@2f0dffa
08-21 15:30:53.209 19375-19439/mytag V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@a29b9ab by -3 
08-21 15:30:53.209 19375-19404/mytag V/FileDownloader.DownloadTaskHunter: call start Url[http://172.16.100.140/appstore/api/application/download?apkId=9], Path[/storage/emulated/0/Android/data/mytag/cache/apk/com.tencent.tmgp.cf.apk] Listener[mytag.widget.download.FileDownLoadListerner@861ea2], Tag[9]
08-21 15:30:53.210 19375-19404/mytag V/FileDownloader.DownloadTaskHunter: the task[765815484] has been into the launch pool.
08-21 15:30:53.211 19375-19440/mytag D/FileDownloader.FileDownloadMessenger: notify begin 765815484@com.liulishuo.filedownloader.DownloadTask@35d01c6
08-21 15:30:53.211 19375-19440/mytag V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@a484587 by 11 
08-21 15:30:53.211 19375-19440/mytag V/FileDownloader.FileDownloadList: add list in all 765815484@com.liulishuo.filedownloader.DownloadTask@35d01c6 11 1
08-21 15:30:53.212 19375-19440/mytag D/FileDownloader.MessageSnapshotGate: ~~~callback 765815484 old[11] new[-3] 1
08-21 15:30:53.212 19375-19440/mytag V/FileDownloader.FileDownloadList: remove 765815484@com.liulishuo.filedownloader.DownloadTask@35d01c6 left -3 0
08-21 15:30:53.212 19375-19440/mytag D/FileDownloader.FileDownloadMessenger: notify block completed 765815484@com.liulishuo.filedownloader.DownloadTask@35d01c6 FileDownloader-LauncherTask3
08-21 15:30:53.213 19375-19440/mytag D/FileDownloader.FileDownloadMessenger: notify completed 765815484@com.liulishuo.filedownloader.DownloadTask@35d01c6
08-21 15:30:53.213 19375-19440/mytag V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@a484587 by -3 
08-21 15:30:53.214 19375-19404/mytag V/FileDownloader.DownloadTaskHunter: call start Url[http://172.16.100.140/appstore/api/application/download?apkId=10], Path[/storage/emulated/0/Android/data/mytag/cache/apk/com.tencent.tmgp.sgame.apk] Listener[mytag.widget.download.FileDownLoadListerner@9bc9733], Tag[10]
08-21 15:30:53.215 19375-19435/mytag D/FileDownloader.FileDownloadMessenger: notify begin -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4
08-21 15:30:53.215 19375-19404/mytag V/FileDownloader.DownloadTaskHunter: the task[-564552580] has been into the launch pool.
08-21 15:30:53.215 19375-19435/mytag V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:start com.liulishuo.filedownloader.DownloadTaskHunter@2c1d0dd by 11 
08-21 15:30:53.215 19375-19435/mytag V/FileDownloader.FileDownloadList: add list in all -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4 11 1
08-21 15:30:53.216 19375-19435/mytag D/FileDownloader.FileDownloadManager: request start the task with url(http://172.16.100.140/appstore/api/application/download?apkId=10) path(/storage/emulated/0/Android/data/mytag/cache/apk/com.tencent.tmgp.sgame.apk) isDirectory(FALSE)
08-21 15:30:53.241 19375-19446/mytag D/FileDownloader.MessageSnapshotGate: ~~~callback -564552580 old[11] new[1] 1
08-21 15:30:53.241 19375-19446/mytag D/FileDownloader.FileDownloadMessenger: notify pending -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4
08-21 15:30:53.244 19375-19446/mytag D/FileDownloader.MessageSnapshotGate: ~~~callback -564552580 old[1] new[6] 1
08-21 15:30:53.244 19375-19446/mytag D/FileDownloader.FileDownloadMessenger: notify started -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4
08-21 15:30:53.269 19375-19447/mytag D/FileDownloader.DownloadMgrInitialParams: initial FileDownloader manager with the customize connection creator: com.liulishuo.filedownloader.connection.FileDownloadUrlConnection$Creator@70f9dd9
08-21 15:30:53.277 19375-19447/mytag D/FileDownloader.ConnectTask: -564552580 request header {If-Match=["2463D5F9F365D43E45DC7C395710AE7F"], Range=[bytes=219627069-]}
08-21 15:30:53.334 19375-19447/mytag D/FileDownloader.FileDownloadUtils: etag find "2463D5F9F365D43E45DC7C395710AE7F" for task(-564552580)
08-21 15:30:53.339 19375-19446/mytag D/FileDownloader.MessageSnapshotGate: ~~~callback -564552580 old[6] new[2] 1
08-21 15:30:53.339 19375-19446/mytag D/FileDownloader.FileDownloadMessenger: notify connected -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4
08-21 15:30:53.345 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: fetch data with multiple connection(count: [5]) for task[-564552580]
08-21 15:30:53.345 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: pass connection[-564552580], because it has been completed
08-21 15:30:53.346 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[-564552580] index[1] range[44363664, 88727327) current offset(86536075)
08-21 15:30:53.347 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: pass connection[-564552580], because it has been completed
08-21 15:30:53.347 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: pass connection[-564552580], because it has been completed
08-21 15:30:53.347 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[-564552580] index[4] range[177454656, 0) current offset(221818322)
08-21 15:30:53.349 19375-19458/mytag D/FileDownloader.ConnectTask: -564552580 request header {If-Match=["2463D5F9F365D43E45DC7C395710AE7F"], Range=[bytes=86536075-88727327]}
08-21 15:30:53.351 19375-19459/mytag D/FileDownloader.ConnectTask: -564552580 request header {If-Match=["2463D5F9F365D43E45DC7C395710AE7F"], Range=[bytes=221818322-]}
08-21 15:30:53.395 19375-19458/mytag D/FileDownloader.DownloadRunnable: the connection[1] for -564552580, is connected range[44363664, 88727327) current offset[86536075] with code[206]
08-21 15:30:53.396 19375-19458/mytag D/FileDownloader.FetchDataTask: start fetch(1): range [44363664, 88727327), seek to[86536075]
08-21 15:30:53.399 19375-19446/mytag D/FileDownloader.MessageSnapshotGate: ~~~callback -564552580 old[2] new[3] 1
08-21 15:30:53.399 19375-19446/mytag D/FileDownloader.FileDownloadMessenger: notify progress -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4 219628449 221818322
08-21 15:30:53.402 19375-19459/mytag D/FileDownloader.DownloadRunnable: the connection[4] for -564552580, is connected range[177454656, 0) current offset[221818322] with code[416]
08-21 15:30:53.408 19375-19458/mytag D/FileDownloader.FetchDataTask: require sync id[-564552580] index[1] offset[86537455], consume[7]
08-21 15:30:53.411 19375-19446/mytag D/FileDownloader.MessageSnapshotGate: ~~~callback -564552580 old[3] new[-1] 1
08-21 15:30:53.411 19375-19446/mytag V/FileDownloader.FileDownloadList: remove -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4 left -1 0
08-21 15:30:53.411 19375-19446/mytag D/FileDownloader.FileDownloadMessenger: notify error -564552580@com.liulishuo.filedownloader.DownloadTask@35eecb4 java.net.SocketException: Connection failed with code[416] on task[-564552580], which is changed after verify connection, so please try again.
08-21 15:30:53.411 19375-19446/mytag V/FileDownloader.DownloadTaskHunter: filedownloader:lifecycle:over com.liulishuo.filedownloader.DownloadTaskHunter@2c1d0dd by -1 
08-21 15:30:53.515 19375-19458/mytag D/FileDownloader.FetchDataTask: require sync id[-564552580] index[1] offset[86537455], consume[5]
08-21 15:30:53.515 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [-564552580] TRUE FALSE
08-21 15:30:53.515 19375-19447/mytag D/FileDownloader.DownloadLaunchRunnable: finish sub-task for [-564552580] TRUE FALSE

**Comment by like001** [comment]
D/FileDownloader.DownloadRunnable: the connection[4] for -564552580, is connected range[177454656, 0) current offset[221818322] with code[416]
好像问题在这里

**Comment by Jacksgong** [comment]
@like001 不是的，这边看日志，第一个请求返回了206:

```
08-21 15:30:53.349 19375-19458/mytag D/FileDownloader.ConnectTask: -564552580 request header {If-Match=["2463D5F9F365D43E45DC7C395710AE7F"], Range=[bytes=86536075-88727327]}
08-21 15:30:53.395 19375-19458/mytag D/FileDownloader.DownloadRunnable: the connection[1] for -564552580, is connected range[44363664, 88727327) current offset[86536075] with code[206]
```

有问题的是第二个请求返回了416:

```
08-21 15:30:53.351 19375-19459/mytag D/FileDownloader.ConnectTask: -564552580 request header {If-Match=["2463D5F9F365D43E45DC7C395710AE7F"], Range=[bytes=221818322-]}
08-21 15:30:53.402 19375-19459/mytag D/FileDownloader.DownloadRunnable: the connection[4] for -564552580, is connected range[177454656, 0) current offset[221818322] with code[416]
```


---

也就是说: 这个Range: `Range=[bytes=221818322-]`，服务端无法接受。

也就是说: 这个最后一个Range存在问题，虽然日志中没有提供文件的大小，但是根据分块拆分来看，每块大小应该是`44363664`，这里根据最后一块的起始`177454656`，目前偏移``，计算出这块应该是已经下载完成，这里确实存在BUG。

---


### 该BUG出现的实际

这个是一个高LEVEL BUG，这个BUG在断点续传前最后一块已经下载完成的时候出现。

### 目前版本应该如何应对

目前的版本，只要[不使用分块下载](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)就没有这个问题。

### 何时修复

由于这个是一个相对出现频率较高的BUG，今天之内会修复发布新版本，多谢🙏.

**Comment by ZY9898** [comment]
哈哈~~~辛苦了，非常感谢

**Comment by sd6352051** [comment]
#733   我在未使用分块下载的情况下 也出现了此问题，
在下载即将结束 暂停 再恢复下载   

此时 暂停  Content-Range: bytes 0-11807182/11807183

恢复下载后 会重新开始 Range: bytes=0-

**Comment by Jacksgong** [comment]
@sd6352051 如果是不同的问题，提个issue，不过提issue之前，最后是参照上面，看下日志，是否是本地给的range是错误的，才416，如果确认是本地问题，把完整的日志贴出来，不过一般来说这块以前也有遇到过，也有可能是服务端错误的返回了416，这边的修复方案只能是退一步重头开始下载。

**Comment by like001** [comment]
@Jacksgong 多谢解答，辛苦了。今天就会修复发布新版本，很欣赏有这样执行力的人！

**Comment by ZY9898** [comment]
是的，我原生没做断点续传，这是日志
 D/FileDownloader.ConnectTask: 547991145 request header {Range=[bytes=2257205-4514409]}
 D/FileDownloader.ConnectTask: 547991145 request header {Range=[bytes=4514410-]}
 D/FileDownloader.ConnectTask: 547991145 request header {Range=[bytes=0-2257204]}
 D/FileDownloader.DownloadRunnable: the connection[1] for 547991145, is connected range[2257205, 4514409) current offset[2257205] with code[416]
 D/FileDownloader.DownloadRunnable: the connection[0] for 547991145, is connected range[0, 2257204) current offset[0] with code[206]

**Comment by Jacksgong** [comment]
@ZY9898 与该Issue修复的的无关，不要在这个issue下面评论。

**Comment by ZY9898** [comment]
好的，谢谢，我们用又拍云的三方存储，我们后台给的测试地址没问题，但是切到正式地址就要报416问题了，我去再找找问题吧

**Comment by Jacksgong** [comment]
@ZY9898 恳请提出新的FileDownloader的BUG，一起完善FileDownloader，但是请别在已经close的issue下进行回复，谢谢。

---

FileDownloader有完善可读的日志，并且最新的该416错误的`exception`也有带回全部的请求头信息与响应头信息，请在提ISSUE前，先阅读尽可能的从日志中以及报的`exception`中获得有效数据，最好是能够在确认是FileDownloader问题后再提Issue，以提高你工作进程的效率。谢谢。
