### ISSUE TITLE
A couple of questions about FileDownloader!

### ISSUE THREAD

**Issue by abforce** [lingochamp/FileDownloader#768]
In my project I've been using Android's Download Manager service, however it frequently fails on an *unreliable* cellular connection. and thereby it sends me a `STATUS_FAILED`. So I'd need a strong downloader which meets the following requirements:
- Not aborting when network is unreachable for a couple of seconds, e.g. one or two seconds.
-  Resumability.
- Supporting HTTPS. 

In short doing its best effort to download the file. Regarding these requirements could FileDownloader be an option for me?

Thank you in advance.

**Comment by Jacksgong** [comment]
> Not aborting when network is unreachable for a couple of seconds, e.g. one or two seconds.

Please handle this by yourself because it's handled would be different with different features, normally it's recommended to toast a dialog let user choice whether need continues to download when the network is unreachable for a couple of seconds and it's very easy to handle this thing on the up layer logic.

> Resumability.

yes.

> Supporting HTTPS.

yes, but this is not the FileDownloader job, FileDownloader supports you customize your own `FileDownloadConnection` and the default one is using `UrlConnection` which handle `http` and `https` case.

**Comment by abforce** [comment]
Just one thing! Does FileDownloader start its own service in order to not be killed by Android when the calling activity goes away? Particularly for large files, user may leave the activity and it gets destroyed by Android framework.
