### ISSUE TITLE
Downloadingfile not chunked eather

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#919]
This URL having a issue in download http://www.telegraph.co.uk/content/dam/news/2017/11/11/Lam4_trans_NvBQzQNjv4BqJHrDUa6dqErW26Sw56Or3qMEnM2GVw2Lj-vOsEqwR0o.jpg?imwidth=480

**Comment by rantianhua** [comment]
Please provide specific information, such as the type of issue, the log of FileDownloader.

**Comment by rantianhua** [comment]
I tried the URL you provided, the `FileDownloadGiveUpRetryException` occurred when starting the download. 

# Why the exception occurs?
---

Because the server uses gzip, the `okhttp` will strip Content-Length response header so that FileDownloader cannot get the content length. In the meantime, the file is not chunked, so the exception is thrown.

# Is it a bug?
---

Actually not, you can ignore this case by config `http.lenient=true` in the `filedownloader.properties`. And the exception message is very clear for that:
```
com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: can't know the size of the download file, and its Transfer-Encoding is not Chunked either. you can ignore such exception by add http.lenient=true to the filedownloader.properties
```

# Any more elegant solution?

---

Yes! We will get file size from `Content-Range` header instead `Content-Length` in 1.7.0. And that is a better way to get the size of the content.

**Comment by Jeffin21** [comment]
When the 1.7.0 coming out ?

**Comment by rantianhua** [comment]
Before 2017.02.05!

发自我的 iPhone
