### ISSUE TITLE
Data losing on multiple downloads  

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#931]
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedOutputStream.write(byte[], int, int)' on a null object reference
01-27 15:39:52.726 2404-10297/com.gagate.gdm W/System.err:     at com.liulishuo.filedownloader.stream.FileDownloadRandomAccessFile.write(FileDownloadRandomAccessFile.java:108)
01-27 15:39:52.726 2404-10297/com.gagate.gdm W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:143)
01-27 15:39:52.726 2404-10297/ W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:125)
01-27 15:39:52.726 2404-10297/ W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
01-27 15:39:52.726 2404-10297/W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-27 15:39:52.726 2404-10297/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-27 15:39:52.726 2404-10297/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-27 15:39:52.728 2404-10297/ W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by rantianhua** [comment]
Please tell me the version you use!

Do you custom the `FileDownloadHelper.OutputStreamCreator `?

**Comment by rantianhua** [comment]
Thanks your report! I will check it tomorrow. Could you tell me how to reproduce it?

发自我的 iPhone

**Comment by Jeffin21** [comment]
You mean the bug ? Download 3 files same time

**Comment by Jeffin21** [comment]
Please add the fix tomorrow, Eagerly waiting for the fix!!

**Comment by rantianhua** [comment]
@Jeffin21 Sorry, i can't reproduce the problem using `MultitaskTestActivity`, so can you give me the github address of your demo?

**Comment by Jeffin21** [comment]
I’m using the latest library. Nothing more

**Comment by Jeffin21** [comment]
Please check task demo activity.

**Comment by rantianhua** [comment]
I have checked all demo, but I still cannot reproduce your problem. So, please show your codes for solving the problem quickly and effectively.

**Comment by rantianhua** [comment]
@Jeffin21 
I view the log you provided again, and I have some doubts about it.  

---
The NPE occurred in the 108th line of `FileDownloadRandomAccessFile` class, however, this class just has 82 total lines in the latest master branch. So, could you please tell me which version and which branch you use?

---

I also checked the 143th line of `FetchDataTask`:
```
 outputStream.write(buff, 0, byteCount);
```
If there is NPE occuring, it means `outputStream` is null, which is created by `FileDownloadHelper.OutputStreamCreator`. The default implementation of the interface is`FileDownloadRandomAccessFile.Creator`:
```
public static class Creator implements FileDownloadHelper.OutputStreamCreator {

        @Override
        public FileDownloadOutputStream create(File file) throws IOException {
            return new FileDownloadRandomAccessFile(file);
        }

        @Override
        public boolean supportSeek() {
            return true;
        }
}
```
You can see that the default implementation is no possible to return null.

---  
By the way, you can also debug the code and find the specific problem because this is an open source library. 

Looking forward to your reply.

**Comment by Jeffin21** [comment]
thanks for you're time , the problems coz of shironasa black hands :D

**Comment by rantianhua** [comment]
Could you please tell me what's the real problem? Is it a bug in the library?

**Comment by Jeffin21** [comment]
@rantianhua we just changed some codes so it effected the download engine.

**Comment by rantianhua** [comment]
Ok, I get it.
